Homework 6 for lesson 8
olenaklm/qa_automation_js pull request #5
Opened 2023-11-16 10:28 UTC by olenaklm

Please review my homework 6 for lesson 8

2023-11-16 20:09 UTC, Art-auto commented on homeworks/lesson_8_hw.js
> +   //Object.freeze(newDev);
цей спосіб заборонить зміну всіх полів, зроби це лише для id поля

2023-11-16 20:11 UTC, Art-auto commented on homeworks/modules/employee.js
> +    }
Out of scope

2023-11-16 20:12 UTC, Art-auto requested changes
Заміни метод Object.freeze()

2023-11-16 21:57 UTC, olenaklm commented on homeworks/lesson_8_hw.js
> +   //Object.freeze(newDev);
Done

2023-11-19 15:19 UTC, Art-auto commented on homeworks/lesson_8_hw.js
> +  //   value: 1,
```suggestion
  //   value: newDev.id,
```
Так значення залишиться тим самим, що і було зпочатку

2023-11-19 15:20 UTC, Art-auto approved these changes
В загальному все добре

2023-11-27 19:59 UTC, merged